name: 'Run regression queries'
description: 'Uses the git branch as the docker tag and pushes the container'
inputs:
  engine:
    description: 'The target engine to run queries on'
    required: true
  queries:
    description: 'The query set or pattern'
    required: true
# outputs:
#   tag:
#     description: 'Is the tag, which was pushed'
runs:
  using: composite
  steps:      
  - name: setup
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -yq cmake bison flex build-essential binutils-dev libldap2-dev libcppunit-dev libicu-dev libxslt1-dev zlib1g-dev libboost-regex-dev libarchive-dev libapr1-dev nodejs libaprutil1-dev libiberty-dev libhiredis-dev libtbb-dev git
      sudo apt-get install -yq libxalan-c-dev libnuma-dev nodejs libevent-dev libatlas-base-dev libblas-dev python3-dev default-libmysqlclient-dev libsqlite3-dev libmemcached-dev libcurl4-openssl-dev pkg-config libtool autotools-dev automake libssl-dev

  - name: run
    shell: bash
    run: |
      source install/opt/HPCCSystems/sbin/hpcc_setenv
      install/opt/HPCCSystems/etc/init.d/hpcc-init start
      cd install/opt/HPCCSystems/testing/regress
      ./ecl-test query --pq 2 --target ${{ inputs.engine }} --excludeclass embedded,3rdparty,spray ${{ inputs.queries }}
