name: 'Publish HPCC Platform'
description: 'Uses the git branch as the docker tag and pushes the container'
inputs:
  build_ver:
    description: 'The label (git tag) for the version you would like to build and push'
    required: false
  build_user:
    description: 'The owner of the HPCC-Platform repository'
    required: false
  username:
    description: 'The login username for docker hub'
    required: true
  password:
    description: 'The login password for docker hub'
    required: true
  build_type:
    description: 'The build type - Debug, RelWithDebInfo, or Release'
    required: false
  build_label:
    description: 'The docker version tag'
    required: false
  docker_repo:
    description: 'The name of the docker repositor to pull and push to/from'
    required: false
  latest:
    description: 'Set to 1 to also tag as latest when maturity is release'
    required: false
outputs:
  tag:
    description: 'Is the tag, which was pushed'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: ./dockerfiles
      with:
        build_ver: ${{ inputs.build_ver }}
        build_user: ${{ inputs.build_user }}
        build_type: ${{ inputs.build_type }}
        build_label: ${{ inputs.build_label }}
        docker_repo: ${{ inputs.docker_repo }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        latest: ${{ inputs.latest }}
    - name: Notify on failure
      uses: hpcc-systems/action-send-mail@v2
      if: ${{ failure() }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.GMAIL_USER}}
        password: ${{secrets.GMAIL_PW}}
        subject: Github Actions job result
        body: Build job of ${{github.repository}} failed!
        to: ${{secrets.GMAIL_RECIPIENTS}}
        from: Github Actions
