#!/usr/bin/env python3
"""
Plot daily storage account usage from CSV files generated by analyze_storage_usage.py

Visualizes storage usage trends across Azure storage accounts over time with two graphs:
1. Total storage usage aggregated across all accounts
2. Per-account storage usage trends

Input:
    CSV file with columns: Date, StorageAccount, UsedGB, BlobGB, FileGB, TableGB, QueueGB
    Expected to be produced by: analyze_storage_usage.py --daily --by-account --format csv

Usage:
    python3 plot_analyze_storage_usage.py <csv_file>

Example:
    python3 plot_analyze_storage_usage.py us-prod400thor-prod.storage-daily-by-account.csv

Requirements:
    pip install matplotlib
"""

import sys
import csv
from datetime import datetime
from collections import defaultdict
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

def parse_csv(filename):
    """Parse CSV file and return data grouped by date and storage account."""
    data = defaultdict(lambda: defaultdict(float))
    dates = set()
    accounts = set()
    
    with open(filename, 'r') as f:
        # Skip comment lines
        lines = [line for line in f if not line.startswith('#')]
    
    reader = csv.DictReader(lines)
    for row in reader:
        date = datetime.strptime(row['Date'], '%Y-%m-%d')
        account = row['StorageAccount']
        used_gb = float(row['UsedGB'])
        
        data[date][account] = used_gb
        dates.add(date)
        accounts.add(account)
    
    return data, sorted(dates), sorted(accounts)

def plot_total_usage(data, dates):
    """Plot total storage usage across all accounts over time."""
    totals = [sum(data[date].values()) for date in dates]
    
    plt.figure(figsize=(12, 6))
    plt.plot(dates, totals, marker='o', linewidth=2, markersize=6)
    plt.xlabel('Date')
    plt.ylabel('Storage Usage (GB)')
    plt.title('Total Storage Usage Across All Accounts')
    plt.grid(True, alpha=0.3)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gcf().autofmt_xdate()
    
    # Add value labels on points
    for date, total in zip(dates, totals):
        plt.annotate(f'{total:,.0f}', (date, total), 
                    textcoords="offset points", xytext=(0,10), 
                    ha='center', fontsize=8)
    
    plt.tight_layout()
    plt.show()

def plot_per_account_usage(data, dates, accounts):
    """Plot storage usage per account over time."""
    plt.figure(figsize=(14, 8))
    
    for account in accounts:
        usage = [data[date].get(account, 0) for date in dates]
        plt.plot(dates, usage, marker='o', label=account, linewidth=1.5, markersize=4)
    
    plt.xlabel('Date')
    plt.ylabel('Storage Usage (GB)')
    plt.title('Storage Usage by Account')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
    plt.grid(True, alpha=0.3)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gcf().autofmt_xdate()
    plt.tight_layout()
    plt.show()

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <csv_file>")
        sys.exit(1)
    
    filename = sys.argv[1]
    
    try:
        data, dates, accounts = parse_csv(filename)
        
        print(f"Loaded data:")
        print(f"  Date range: {dates[0].strftime('%Y-%m-%d')} to {dates[-1].strftime('%Y-%m-%d')}")
        print(f"  Storage accounts: {len(accounts)}")
        print(f"  Total data points: {sum(len(data[date]) for date in dates)}")
        print()
        
        # Plot total usage
        plot_total_usage(data, dates)
        
        # Plot per-account usage
        plot_per_account_usage(data, dates, accounts)
        
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()
