{{ range $.Values.dali -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .name | quote }}
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
    spec:
      containers:
      - name: {{ .name | quote }}
        args: [
                # {{ include "hpcc.configArg" . }} - dali does not support this yet
              ]
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "dali") | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigVolumeMount" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigVolume" . | indent 6 }}
---
{{- include "hpcc.generateConfigMap" (dict "root" $ "component" "dali" "me" .) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
spec:
  ports:
  - port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    run: {{ .name | quote }}
  type: ClusterIP
---
{{- end }}