{{ range $.Values.esp -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      run: {{ .name | quote }}
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
    spec:
      containers:
      - name: {{ .name | quote }}
        args: [
                # {{ include "hpcc.configArg" . }},
                # {{ include "hpcc.daliArg" $ }}
              ]
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "esp") | indent 8 }}
{{ include "hpcc.addVolumeMounts" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigVolume" . | indent 6 }}
{{ include "hpcc.addVolumes" $ | indent 6 }}
---
{{- include "hpcc.generateConfigMap" (dict "root" $ "component" "esp" "me" .) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    run: {{ .name | quote }}
  type: LoadBalancer
{{- end }}