{{ range $roxie := $.Values.roxie -}}
{{- if $roxie.localSlave -}}
{{- $name := $roxie.name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $roxie.name | quote }}
spec:
  replicas: {{ $roxie.serverReplicas | default 1 }}
  selector:
    matchLabels:
      run: {{ $roxie.name | quote }}
  template:
    metadata:
      labels:
        run: {{ $roxie.name | quote }}
    spec:
      {{- include "hpcc.checkDataStorageHostMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ $roxie.name | quote }}
        args: [
                {{ include "hpcc.configArg" $roxie }},
                {{ include "hpcc.daliArg" $ }},
                "--serverPorts={{ template "hpcc.portListToCommas" $roxie.ports }}", 
                "--localSlave=true",
                "--resolveLocally=false"
              ]
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" . "imagename" "roxie") | indent 8 }}
{{ include "hpcc.addVolumeMounts" . | indent 8 }}
      volumes:
{{ include "hpcc.addConfigVolume" . | indent 6 }}
{{ include "hpcc.addVolumes" $ | indent 6 }}
---
{{- include "hpcc.generateConfigMap" (dict "root" $ "component" "roxie" "me" $roxie ) }}
---
{{- end }}
{{- end }}
 
