name: Docker smoketest build
on:
  push:
    branches:
      - "ghacttst"

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: vars
        id: vars
        run: |
          echo ::set-output name=base_ver::7.12.1
          # echo ::set-output name=container_registry::ghcr.io
          # echo ::set-output name=cr_user::${{ github.repository_owner }}
          echo ::set-output name=container_registry::docker.io
          echo ::set-output name=cr_user::${{ secrets.DOCKER_USERNAME }}
          echo ::set-output name=build_prbase_sha::${{ github.event.pull_request.base.sha }}
          echo ::set-output name=build_prbase_label::${{ github.base_ref }}
          echo ::set-output name=build_pr_label::pr-${{ github.event.number }}-${{ github.sha }}
          echo ::set-output name=build_user::${{ github.actor }}
          echo ::set-output name=build_type::RelWithDebInfo
          echo ::set-output name=use_cppunit::1
          echo ::set-output name=platform_build_base::platform-build-base
          echo ::set-output name=platform_build::platform-build

      - name: tracing
        run: |
          echo "Base ref   = ${{ github.ref }}"
          echo "Action     = ${{ github.action }}"
          echo "Event      = ${{ github.event_name }}"
          echo "Actor      = ${{ github.actor }}"
          echo "Ref        = ${{ github.ref }}"
          echo "base sha   = ${{ github.event.pull_request.base.sha }}"
          echo "Sha        = ${{ github.sha }}"
          echo "github.repository = ${{ github.repository }}"
          echo "repository_owner = ${{ github.repository_owner }}"
          echo "github.workspace = ${{ github.workspace }}"
          echo "runner.workspace = ${{ runner.workspace }}"
          echo "github.event.pull_request.head.repo.owner.login = ${{ github.event.pull_request.head.repo.owner.login }}"
          echo "build_prbase_label = ${{ steps.vars.outputs.build_prbase_label }}"
          echo "build_pr_label = ${{ steps.vars.outputs.build_pr_label }}"

      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # build build-base if missing
      - name: d1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/img1/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            docker.io/jakesmith0/img1:1.1

      # build branch image if missing
      - name: d2
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/img2/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            docker.io/jakesmith0/img2:1.1

