# This is a basic workflow to help you get started with Actions

name: buildit-using-docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#    branches:
#      - notmain
  pull_request:
    branches:
      - notmaster

jobs:
  builditjob:
    runs-on: ubuntu-20.04
    name: A job to build and push docker

    steps:
    - name: vars1
      run: echo GITHUB_ACTOR is ${GITHUB_ACTOR}
    - name: vars2
      run: echo github.actor is ${{ github.actor }}
    - name: vars3
      run: echo github.repository_owner is ${{ github.repository_owner }}
    - name: vars4
      run: echo "CR_PAT is ${{ secrets.CR_PAT }} , is it visible?"

    - name: Checkout
      uses: actions/checkout@v2
#      with:
#        submodules: recursive ## guessing, check

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .github/workflows
        file: .github/workflows/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        build-args: |
          BUILD_USER=${{ github.actor }}
          BASE_BRANCH=master
          BUILD_BRANCH=master-ch1
        tags: |
          ghcr.io/user/app:latest
          ghcr.io/user/app:1.0.0
        secrets: |
          GIT_AUTH_TOKEN=${{ github.token }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

