# This is a basic workflow to help you get started with Actions

name: buildit-using-docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#    branches:
#      - notmain
  pull_request:
    branches:
      - master

jobs:
  builditjob:
    runs-on: ubuntu-20.04
    name: A job to build and push docker

    steps:
    - name: vars1
      run: echo GITHUB_ACTOR is ${GITHUB_ACTOR}
    - name: vars2
      run: echo github.actor is ${{ github.actor }}
    - name: vars3
      run: echo github.repository_owner is ${{ github.repository_owner }}
    - name: vars4
      run: echo base_ref is ${{ github.base_ref }}, head_ref is ${{ github.head_ref }}, ref is ${{ github.ref }}, sha is ${{ github.sha }}
    - name: vars5
      run: echo event - pull_request.base.sha ${{ github.event.pull_request.base.sha }}

#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 1
#        submodules: recursive ## guessing, check

    - name: Download the file
      uses: suisei-cn/actions-download-file@v1
      id: downloadfile  # Remember to give an ID if you need the output
      with:
        url: "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/docker/all/Dockerfile"
        target: dockerctx/
    - name: testing1
      run: svn export "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/docker/all"
    - name: list
      run: ls -ltR
    - name: show
      run: cat dockerctx/Dockerfile
