name: Nightly master build and publish
on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: "Nightly build and publish release container"
    runs-on: ubuntu-latest
    if: github.repository == 'hpcc-systems/HPCC-Platform'
    steps:
      - name: vars
        id: vars
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_ver: "master"
          build_label: "master-${{ steps.vars.outputs.date }}"

      - name: Notify on failure
        uses: hpcc-systems/action-send-mail@v2
        if: ${{ failure() }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GMAIL_PW}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} failed!
          to: ${{secrets.GMAIL_RECIPIENTS}}
          from: Github Actions

