name: pr-label-test

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          echo "github.event_name ${{ github.event_name }}"
          echo "github.event_path ${{ github.event_path }}"
          cat ${{ github.event_path }}
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
      - id: mylabel1
        if: contains(github.event.pull_request.labels.*.name, 'mylabel1')
        run: |
          echo "Found Label match: mylabel1"
      - id: mylabel2
        if: contains(github.event.pull_request.labels.*.name, 'mylabel2')
        run: |
          echo "Found Label match: mylabel2"

