# This is a basic workflow to help you get started with Actions

name: st-docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#    branches:
#      - notmain
  pull_request:
    branches:
      - master

jobs:
  buildit:
    runs-on: ubuntu-20.04
    name: A job to build and push docker

    steps:
    - name: vars
      run: |
        echo GITHUB_ACTOR is ${GITHUB_ACTOR}
        echo base_ref is ${{ github.base_ref }}
        echo head_ref is ${{ github.head_ref }}
        echo ref is ${{ github.ref }}
        echo sha is ${{ github.sha }}
        echo github.actor is ${{ github.actor }}
        echo github.repository_owner is ${{ github.repository_owner }}
        echo event - base.sha ${{ github.event.pull_request.base.sha }}

#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 1
##        submodules: recursive ## guessing, check

    - name: Download files # might be better as a tarball and 1 file download
      run: |
        mkdir -p smoketest/imagectx
        mkdir -p smoketest/basebranchctx
        mkdir -p smoketest/prbranchctx
        mkdir -p smoketest/regresssetupctx
        curl -s --output smoketest/imagectx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/imagectx/Dockerfile"
        curl -s --output smoketest/basebranchctx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/basebranchctx/Dockerfile"
        curl -s --output smoketest/prbranchctx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/prbranchctx/Dockerfile"
        curl -s --output smoketest/regresssetupctx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/regresssetupctx/Dockerfile"
        curl -s --output smoketest/regresssetupctx/entrypoint.sh "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/regresssetupctx/entrypoint.sh"
        curl -s --output smoketest/regresssetupctx/ecl-test.json "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/regresssetupctx/ecl-test.json"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build base image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image --cache-from type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image --cache-to type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image smoketest/imagectx
        docker push
