# NB: --build-arg's must be set for previous ARG's for future parts of multi-stage builds

name: st-docker
env:
  IMAGE_CACHETAG: ghcr.io/${{ github.repository_owner }}/s3moketest-image
  MM_CACHETAG: ghcr.io/${{ github.repository_owner }}/s3moketest-major-minor-base
  BASE_BRANCH_CACHETAG: ghcr.io/${{ github.repository_owner }}/s3moketest-base-branch-build:${{ github.base_ref }}_${{ github.event.pull_request.base.sha }}
  HEAD_BRANCH_CACHETAG: ghcr.io/${{ github.repository_owner }}/s3moketest-head-branch-build:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }}
  REGRESS_CACHETAG: ghcr.io/${{ github.repository_owner }}/s3moketest-regress-setup:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }}

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#    branches:
#      - notmain
  pull_request:
    branches:
      - master

jobs:
  build-and-setup:
    name: Build platform and regress setup container
    runs-on: ubuntu-20.04

    steps:
    - name: vars
      id: vars
      run: |
        echo GITHUB_ACTOR is ${GITHUB_ACTOR}
        echo base_ref is ${{ github.base_ref }}
        echo head_ref is ${{ github.head_ref }}
        echo ref is ${{ github.ref }}
        echo sha is ${{ github.sha }}
        echo github.actor is ${{ github.actor }}
        echo github.repository_owner is ${{ github.repository_owner }}
        echo event - base.sha ${{ github.event.pull_request.base.sha }}
        echo HEAD_BRANCH_CACHETAG - ${{ env.HEAD_BRANCH_CACHETAG }}

    - name: Download files # might be better as a single tarball
      id: dlfiles
      run: |
        mkdir -p smoketest
        curl -s --output smoketest/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest2/Dockerfile"
        curl -s --output smoketest/runregress.sh "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest2/runregress.sh"
        chmod +x smoketest/runregress.sh
        curl -s --output smoketest/ecl-test.json "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest2/ecl-test.json"
        curl -s --output smoketest/getmajorminorbase.sh "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest2/getmajorminorbase.sh"
        chmod +x smoketest/getmajorminorbase.sh
        echo ::set-output name=mmbase-tag::$(smoketest/getmajorminorbase.sh ${{ github.repository_owner }} ${{ github.base_ref }})

    # - name: Set up Docker Buildx
    #   id: buildx
    #   uses: docker/setup-buildx-action@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}

    - name: Build base image
      run: |
        docker build --pull -t ${{env.REGRESS_CACHETAG }} --target base-image smoketest/
        docker push ${{env.REGRESS_CACHETAG }}

    - name: Build major-minor base branch
      run: |
        docker build --pull -t ${{ env.MM_CACHETAG }}:${{ steps.dlfiles.outputs.mmbase-tag }} \
          --target major-minor-base-build \
          --build-arg BASE_REPO=${{ github.repository_owner }} \
          --build-arg MAJOR_MINOR_BASE=${{ steps.dlfiles.outputs.mmbase-tag }} \
          smoketest/
        docker push ${{ env.MM_CACHETAG }}:${{ steps.dlfiles.outputs.mmbase-tag }}

    - name: Build base branch
      run: |
        docker build --pull -t ${{ env.BASE_BRANCH_CACHETAG }} \
          --target base-branch-build \
          --build-arg BASE_REPO=${{ github.repository_owner }} \
          --build-arg MAJOR_MINOR_BASE=${{ steps.dlfiles.outputs.mmbase-tag }} \
          --build-arg BASE_BRANCH=${{ github.base_ref }} \
          --build-arg BASE_SHA=${{ github.event.pull_request.base.sha }} 
          smoketest/
        docker push ${{ env.BASE_BRANCH_CACHETAG }}

    - name: Build head branch
      run: |
        docker build --pull -t ${{ env.HEAD_BRANCH_CACHETAG }} \
          --target head-branch-build \
          --build-arg BASE_REPO=${{ github.repository_owner }} \
          --build-arg MAJOR_MINOR_BASE=${{ steps.dlfiles.outputs.mmbase-tag }} \
          --build-arg BASE_BRANCH=${{ github.base_ref }} \
          --build-arg BASE_SHA=${{ github.event.pull_request.base.sha }} \
          --build-arg HEAD_REPO=${{ github.actor }} \
          --build-arg HEAD_BRANCH=${{ github.ref }} \
          --build-arg HEAD_SHA=${{ github.event.pull_request.head.sha }} \
          smoketest/
        docker push ${{ env.HEAD_BRANCH_CACHETAG }}

    - name: Regress setup
      run: |
        docker build --pull -t ${{ env.REGRESS_CACHETAG }} \
          --target regress-setup \
          --build-arg BASE_REPO=${{ github.repository_owner }} \
          --build-arg MAJOR_MINOR_BASE=${{ steps.dlfiles.outputs.mmbase-tag }} \
          --build-arg BASE_BRANCH=${{ github.base_ref }} \
          --build-arg BASE_SHA=${{ github.event.pull_request.base.sha }} \
          --build-arg HEAD_REPO=${{ github.actor }} \
          --build-arg HEAD_BRANCH=${{ github.ref }} \
          --build-arg HEAD_SHA=${{ github.event.pull_request.head.sha }} \
          smoketest2\
        docker push ${{ env.REGRESS_CACHETAG }} 

  regress-hthor-a-h:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-hthor' ${{ env.REGRESS_CACHETAG }} hthor [a-h]*.ecl

  regress-hthor-i-q:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-hthor' ${{ env.REGRESS_CACHETAG }} hthor [i-q]*.ecl

  regress-hthor-r-z:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-hthor' ${{ env.REGRESS_CACHETAG }} hthor [r-z]*.ecl

  regress-thor-a-h:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-thor' ${{ env.REGRESS_CACHETAG }} thor [a-h]*.ecl

  regress-thor-i-q:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-thor' ${{ env.REGRESS_CACHETAG }} thor [i-q]*.ecl

  regress-thor-r-z:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-thor' ${{ env.REGRESS_CACHETAG }} thor [r-z]*.ecl

  regress-roxie-a-h:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-roxie' ${{ env.REGRESS_CACHETAG }} roxie [a-h]*.ecl

  regress-roxie-i-q:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-roxie' ${{ env.REGRESS_CACHETAG }} roxie [i-q]*.ecl

  regress-roxie-r-z:
    runs-on: ubuntu-20.04
    needs: [ build-and-setup ]
    steps:
    - uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-regress-roxie' ${{ env.REGRESS_CACHETAG }} roxie [r-z]*.ecl

  unittests:
    runs-on: ubuntu-20.04
    needs: build-and-setup
    steps:
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CR_PAT }}
    - run: |
        docker pull ${{ env.REGRESS_CACHETAG }}
        docker run --name 'smoketest-unittests' --entrypoint /hpcc-dev/hpccinstall/opt/HPCCSystems/bin/unittests ${{ env.REGRESS_CACHETAG }}
