name: test4

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  job1:
    name: job1
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        #submodules: recursive
        path: src

    - name: step1
      run: |
        echo this is a test
        #${{ github.workspace }}/src/.github/workflows/testkill

        ls -lt /bin/kill
        which sh
        which bash
        bash -c '(sleep 200 & sleep 200 & sleep 200) & /bin/kill -s TERM -$!'
        echo here

        # sleep 30 &
        # thepid=$!
        # sleep 2
        # echo thepid=${thepid}
        # echo thispid=$$
        # ps -o pid,pgid,args
        # ps aux | grep sleep
        # echo kill -INT -- -${thepid}
        # kill -INT -- -${thepid}
        # ps aux | grep sleep
        # #${{ github.workspace }}/src/.github/workflows/timeoutcmd 8 sleep 30
