# This is a basic workflow to help you get started with Actions

name: st-docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#    branches:
#      - notmain
  pull_request:
    branches:
      - master

jobs:
  buildit:
    runs-on: ubuntu-20.04
    name: A job to build and push docker

    steps:
    - name: vars
      run: |
        echo GITHUB_ACTOR is ${GITHUB_ACTOR}
        echo base_ref is ${{ github.base_ref }}
        echo head_ref is ${{ github.head_ref }}
        echo ref is ${{ github.ref }}
        echo sha is ${{ github.sha }}
        echo github.actor is ${{ github.actor }}
        echo github.repository_owner is ${{ github.repository_owner }}
        echo base.sha ${{ github.context.pull_request.base.sha }}
        echo event - base.sha ${{ github.event.pull_request.base.sha }}

#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 1
##        submodules: recursive ## guessing, check

    - name: Download files # might be better as a tarball and 1 file download
      run: |
        mkdir -p smoketest/imagectx
        mkdir -p smoketest/basebranchctx
        mkdir -p smoketest/prbranchctx
        curl -s --output smoketest/imagectx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/imagectx/Dockerfile"
        curl -s --output smoketest/basebranchctx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/basebranchctx/Dockerfile"
        curl -s --output smoketest/prbranchctx/Dockerfile "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/prbranchctx/Dockerfile"
        curl -s --output smoketest/prbuildctx/entrypoint.sh "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/prbranchctx/entrypoint.sh"
        curl -s --output smoketest/prbranchctx/ecl-test.json "https://raw.githubusercontent.com/${{ github.repository_owner }}/HPCC-Platform/${{ github.sha }}/.github/workflows/smoketest/prbranchctx/ecl-test.json"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build base image
      uses: docker/build-push-action@v2
      with:
        context: smoketest/imagectx
        file: smoketest/imagectx/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        #load: true # NB: forces buildx.with.driver=docker (as opposed to default driver=docker-containerized)
        push: true
        cache-from: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image
        cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image

    - name: Build base branch
      uses: docker/build-push-action@v2
      with:
        context: smoketest/basebranchctx
        file: smoketest/basebranchctx/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        cache-from: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-basebranch:${{ github.base_ref }}
        #cache-to: type=inline
        cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-basebranch:${{ github.base_ref }}
        build-args: |
          IMAGE_BASE=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-image
          GITHUB_REPO_OWNER=${{ github.repository_owner }}
          BASE_BRANCH=${{ github.base_ref }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/smoketest-basebranch:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }}

    - name: Build pr branch
      uses: docker/build-push-action@v2
      with:
        context: smoketest/prbranchctx
        file: smoketest/prbranchctx/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        cache-from: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-prbranch:${{ github.base_ref }}
        #cache-to: type=inline
        cache-to: type=registry,mode=max,ref=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-prbranch:${{ github.base_ref }}
        build-args: |
          IMAGE_BASE=${{ secrets.DOCKERHUB_USERNAME }}/smoketest-basebranch:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }}
          GITHUB_ACTOR=${{ github.actor }}
          BUILD_BRANCH=${{ github.ref }}

        tags: ${{ secrets.DOCKERHUB_USERNAME }}/smoketest-prbranch:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }}

#          BUILDKIT_INLINE_CACHE=1  # not needed when using cache-to: type=inline

#    - name: push to registry
#      run: |
#        docker push ${{ secrets.DOCKERHUB_USERNAME }}/prtestall:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }}

  regress-setup:
    runs-on: ubuntu-20.04
    name: Regression setup job
    needs: buildit
    steps:
    - name: Regression suite setup
      run: docker run --name 'smoketest-setup' ${{ secrets.DOCKERHUB_USERNAME }}/smoketest-prbranch:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }} setup

  regress-hthor:
    runs-on: ubuntu-20.04
    name: Regression hthor job
    needs: [ buildit, regress-setup ]
    steps:
    - name: Regression suite hthor
      run: docker run --name 'smoketest-hthor' ${{ secrets.DOCKERHUB_USERNAME }}/prtestall:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }} hthor

  regress-thor:
    runs-on: ubuntu-20.04
    name: Regression thor job
    needs: [ buildit, regress-setup ]
    steps:
    - name: Regression suite thor
      run: docker run --name 'smoketest-thor' ${{ secrets.DOCKERHUB_USERNAME }}/prtestall:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }} thor

  regress-roxie:
    runs-on: ubuntu-20.04
    name: Regression roxie job
    needs: [ buildit, regress-setup ]
    steps:
    - name: Regression suite roxie
      run: docker run --name 'smoketest-roxie' ${{ secrets.DOCKERHUB_USERNAME }}/prtestall:${{ github.head_ref }}_${{ github.event.pull_request.head.sha }} roxie
