name: test3

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  job1:
    name: job1
    runs-on: ubuntu-20.04

    steps:
    - name: step1
      run: |
        echo this is a test
        ((trap "echo hello" EXIT; sleep 300) & wait)
