name: Check that eclhelper interface has not changed

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"

jobs:
  build:
    name: "Check eclhelper interface"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pr
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch base
        run: |
          git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin ${{ github.event.pull_request.base.sha }}
      - name: Check eclhelper
        run: |
          git diff ${{ github.event.pull_request.base.sha }} --exit-code -- rtl/include/eclhelper.hpp
