name: Run helm chart tests

on:
  push:
    branches:
      - "helm-fix"
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.8.*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  pre_job:
     # continue-on-error: true # Uncomment once integration is finished
     runs-on: ubuntu-20.04
     # Map a step output to a job output
     outputs:
       helm: ${{ steps.skip_check.outputs.helm }}
     steps:
       - id: skip_check
         uses: hpcc-systems/github-actions/changed-modules@main
         with:
           github_token: ${{ github.token }}
  build:
    name: "Check helm chart lint"
    runs-on: ubuntu-20.04
    needs: pre_job
    if: ${{ github.repository == 'hpcc-systems/HPCC-Platform' && needs.pre_job.outputs.helm }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - uses: azure/setup-helm@v1
        with:
          version: 'latest'
        id: install
      - name: Install additional tools
        working-directory: ./testing/helm
        run: wget https://github.com/zegl/kube-score/releases/download/v1.8.1/kube-score_1.8.1_linux_amd64 && sudo mv kube-score_1.8.1_linux_amd64 /usr/bin/kube-score && sudo chmod +x /usr/bin/kube-score
      - name: Test
        working-directory: ./testing/helm
        run: ./run.sh
